import { auth } from '@/auth';
import prisma from '@/lib/prisma';
import { format } from 'date-fns';
import { id as idLocale } from 'date-fns/locale';
import { notFound, redirect } from 'next/navigation';

export default async function InvoicePage({ params }: { params: { id: string } }) {
    // Await params as per Next.js 15+ requirements if applicable, but for 14 it's sync. 
    // Wait, checking package.json: "next": "16.0.8". 
    // In Next 15/16, params is a Promise.
    const { id } = await params;

    const session = await auth();
    if (!session?.user) redirect('/login');

    const transaction = await prisma.transaction.findUnique({
        where: { id },
        include: {
            customer: true,
            company: true,
            item: true
        }
    });

    if (!transaction) notFound();

    // Basic Access Control
    if (transaction.companyId !== session.user.companyId && session.user.role !== 'OWNER') {
        return <div className="p-10 text-center text-red-500">Unauthorized Access</div>;
    }

    const formatCurrency = (val: number) => new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', minimumFractionDigits: 0 }).format(val);

    return (
        <div className="min-h-screen bg-slate-100 p-8 flex justify-center items-start print:bg-white print:p-0">
            <div className="bg-white shadow-lg w-[210mm] min-h-[297mm] p-[10mm] relative print:shadow-none print:w-full">

                {/* Print Button (Hidden when printing) */}
                <div className="absolute top-4 right-[-80px] print:hidden">
                    <button
                        id="print-btn"
                        className="bg-blue-600 text-white p-3 rounded-full shadow hover:bg-blue-700"
                        title="Print Invoice"
                    >
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polyline points="6 9 6 2 18 2 18 9"></polyline><path d="M6 18H4a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-2"></path><rect x="6" y="14" width="12" height="8"></rect></svg>
                    </button>
                </div>

                {/* Header */}
                <div className="flex justify-between items-start border-b pb-8 mb-8">
                    <div>
                        <h1 className="text-3xl font-bold text-slate-900 mb-2">{transaction.company.name}</h1>
                        <p className="text-slate-500 text-sm max-w-[300px]">
                            Document generated by Finentry
                        </p>
                    </div>
                    <div className="text-right">
                        <h2 className="text-2xl font-bold text-blue-600 mb-1">INVOICE</h2>
                        <p className="font-mono text-slate-600">{transaction.invoiceNumber || 'DRAFT'}</p>
                    </div>
                </div>

                {/* Info Grid */}
                <div className="grid grid-cols-2 gap-8 mb-8">
                    <div>
                        <h3 className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-1">Bill To</h3>
                        <div className="font-medium text-slate-800">{transaction.customer?.name || 'Cash Customer'}</div>
                        <div className="text-slate-500 text-sm mt-1">{transaction.customer?.address || '-'}</div>
                        <div className="text-slate-500 text-sm">{transaction.customer?.contact || '-'}</div>
                    </div>
                    <div className="text-right pb-4">
                        <div className="mb-2">
                            <span className="text-slate-500 text-sm mr-4">Invoice Date:</span>
                            <span className="font-medium">{format(new Date(transaction.date), 'dd MMMM yyyy', { locale: idLocale })}</span>
                        </div>
                    </div>
                </div>

                {/* Table */}
                <table className="w-full mb-8">
                    <thead>
                        <tr className="bg-slate-50 border-y border-slate-200">
                            <th className="py-3 pl-4 text-left text-sm font-semibold text-slate-600">Item Description</th>
                            <th className="py-3 text-right text-sm font-semibold text-slate-600">Qty</th>
                            <th className="py-3 text-right text-sm font-semibold text-slate-600">Price</th>
                            <th className="py-3 pr-4 text-right text-sm font-semibold text-slate-600">Total</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr className="border-b border-slate-100">
                            <td className="py-4 pl-4">
                                <div className="font-medium text-slate-900">{transaction.item.name}</div>
                                <div className="text-slate-500 text-sm">{transaction.notes}</div>
                            </td>
                            <td className="py-4 text-right text-slate-600">{transaction.quantity} {transaction.item.unit}</td>
                            <td className="py-4 text-right text-slate-600">{formatCurrency(transaction.sellPrice)}</td>
                            <td className="py-4 pr-4 text-right font-medium text-slate-900">{formatCurrency(transaction.revenue)}</td>
                        </tr>
                    </tbody>
                </table>

                {/* Totals */}
                <div className="flex justify-end mb-12">
                    <div className="w-1/3 space-y-2">
                        <div className="flex justify-between text-slate-600">
                            <span>Subtotal</span>
                            <span>{formatCurrency(transaction.revenue)}</span>
                        </div>
                        <div className="flex justify-between border-t border-slate-200 pt-2 text-lg font-bold text-slate-900">
                            <span>Total</span>
                            <span>{formatCurrency(transaction.revenue)}</span>
                        </div>
                    </div>
                </div>

                {/* Footer */}
                <div className="border-t pt-8 mt-auto text-center text-slate-500 text-sm">
                    <p>Thank you for your business!</p>
                </div>

                <script dangerouslySetInnerHTML={{
                    __html: `
                    document.querySelector('button[title="Print Invoice"]').onclick = () => window.print();
                `}} />
            </div>
        </div>
    );
}
